name: Health check

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:
jobs:
  check_deployed_service:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex-frosty-dew-5836.fly.dev/health
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
